### ISSUE TITLE
Password is taking space

### ISSUE THREAD

**Issue by Sesslyn041215** [fssa-batch3/alagappan.kumaravel__web_project#12]
Password in sign up is taking space.

```
Path:      /pages/login&signup/signup1.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--sportzhub.netlify.app%2Fpages%2Flogin%26signup%2Fsignup1.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--sportzhub.netlify.app/pages/login&signup/signup1.html)

**Comment by alagappan2578** [comment]
I inset that space purposely

**Comment by Sesslyn041215** [comment]
Issue closed
