### ISSUE TITLE
Documentation confusion

### ISSUE THREAD

**Issue by Sesslyn041215** [fssa-batch3/alagappan.kumaravel__web_project#14]
As per your documentation , there is no join team button. How can the team player and the captian are differntiate while loogging in.

```
Path:      /pages/homepage/hpexist.html?unique_id=8778061108
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--sportzhub.netlify.app%2Fpages%2Fhomepage%2Fhpexist.html%3Funique_id%3D8778061108&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--sportzhub.netlify.app/pages/homepage/hpexist.html?unique_id=8778061108)

**Comment by alagappan2578** [comment]
issue solved

**Comment by Sesslyn041215** [comment]
It has been solved.
