### ISSUE TITLE
Switch button is not showing

### ISSUE THREAD

**Issue by Sesslyn041215** [fssa-batch3/alagappan.kumaravel__web_project#18]
Like the remove button after toggling off / on button switch button is not showing.

```
Path:      /pages/profile/teamprofile.html?unique_id=9952393568
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--sportzhub.netlify.app%2Fpages%2Fprofile%2Fteamprofile.html%3Funique_id%3D9952393568&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--sportzhub.netlify.app/pages/profile/teamprofile.html?unique_id=9952393568)

**Comment by alagappan2578** [comment]
issue solved

**Comment by Sesslyn041215** [comment]
It has been solved
